### ISSUE TITLE
[Firefox or Chrome, or both] Various Passives bugs

### ISSUE THREAD

**Issue by ABCBoyCEO** [James1011R/ceopiecemaker#12]
I would divide this into multiple issues, but I'm too lazy.

![bug 1](https://user-images.githubusercontent.com/31487965/30107774-5978a7c8-9332-11e7-8613-02d6d8f40909.gif)
![bug 2](https://user-images.githubusercontent.com/31487965/30107775-597b69ae-9332-11e7-997d-e1fa5e71741f.gif)
![bug 3](https://user-images.githubusercontent.com/31487965/30107773-597813a8-9332-11e7-8754-4d73d43982b7.gif)
![bug 4](https://user-images.githubusercontent.com/31487965/30107772-5975e9a2-9332-11e7-895d-3c5b017c1da5.gif)

See it for yourself, and stop denying the fact that they exist.

**Comment by James1011R** [comment]
Bugs 1, 3, and 4 I've tested in both Firefox and Browserling Chrome, not confirmed to exist.

Bug 2 I will attempt to fix.

**Comment by ABCBoyCEO** [comment]
What do you mean "not confirmed to exist"? I've even provided gif proof that it does. stop being such a fascist. 

These bugs are only producible from Firefox 55 onward, if you're using some old foxes then it probably will still work (as the existing code is written for the old `<br>`-seperating Firefox behavior.

For the Chrome, I'm using Chromium, latest version.

**Comment by James1011R** [comment]
PMC:UPLE is dead. No, seriously.
