### ISSUE TITLE
[Firefox & Chrome] Visual/Minor: Inconsistent mouse icons on button hover

### ISSUE THREAD

**Issue by maingi2** [James1011R/ceopiecemaker#7]
What the title says. In main button select bar, the buttons show the "hovering text" icon. In Action/Share section, buttons don't show a different cursor icon. In Drawing Tools, the buttons actually have a "selected" icon. Want to merge in the future.

**Comment by James1011R** [comment]
Oddly enough the the ability text popup in the Action Menu shows the selected cursor for a brief moment.
